export {
  ScannerView,
  defaultScanRegion,
  performanceModes,
  type ScannerViewProps,
  type ScannerViewRef,
  type CameraPosition,
  type Resolution,
  type FocusMode,
  type OverlayMode,
  type HapticStyle,
  type PerformanceMode,
  type BarcodeFormat,
  type ScanRegion,
  type ScanResult,
  type CameraReadyEvent,
  type ErrorEvent,
  type CameraMetrics,
} from './ScannerView';

export {
  Scanner,
  type ScanResult as LegacyScanResult,
  type ScanRegionConfig,
  type BoundingBoxConfig,
  type DetectionType,
  type FaceDetectionConfig,
  type FaceResult,
  type FaceLandmarkPoint,
  type FacesDetectedEvent,
} from './Scanner';
